---
development:
  DB_FILENAME: app/infrastructure/database/local/dev.db
  # DB_NAME: <LOCALHOST POSTGRESQL DATABASE NAME>

test:
  DB_FILENAME: app/infrastructure/database/local/test.db
  # DB_NAME: <LOCALHOST POSTGRESQL DATABASE NAME>
