---
# Name the file secrets.yml

development:
  GITHUB_TOKEN: <personal access token for googlemap api>
  SESSION_SECRET: <session secret>

test:
  GITHUB_TOKEN: <personal access token for googlemap api>
  SESSION_SECRET: <session secret>
production:
  GITHUB_TOKEN: <personal access token for googlemap api>
  SESSION_SECRET: <session secret>
