---
# Name the file secrets.yml

development:
  GITHUB_TOKEN: <personal access token for googlemap api>

test:
  GITHUB_TOKEN: <personal access token for googlemap api>

production:
  GITHUB_TOKEN: <personal access token for googlemap api>
